version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - qdrant
    command: ["python", "-m", "src.main"]

  qdrant:
    image: qdrant/qdrant
    restart: always
    volumes:
      - qdrant_prod_data:/qdrant/storage

volumes:
  qdrant_prod_data: 