from .agents import VectorDBAgents
from .tasks import VectorDBTasks
from .retrieval import QdrantRetriever
from crewai import Crew
import logging

# Get logger
logger = logging.getLogger(__name__)

class VectorDBIntegration:
    """
    Integration between Qdrant vector retrieval and agent-based response generation.
    This class combines vector database retrieval with agent-based processing to
    generate high-quality responses in Sergey's style.
    """
    
    def __init__(self, collection_name="context-main3", top_k=3, max_iterations=3, process_timeout=300):
        """Initialize the integration components."""
        logger.info(f"Initializing VectorDBIntegration with collection: {collection_name}, top_k: {top_k}, max_iterations: {max_iterations}")
        
        # Initialize vector retriever
        self.retriever = QdrantRetriever(collection_name=collection_name, top_k=top_k)
        
        # Initialize agents
        self.agents = VectorDBAgents()
        
        # Initialize tasks
        self.tasks = VectorDBTasks()
        
        # Set iteration limits
        self.max_iterations = max_iterations
        self.process_timeout = process_timeout
        
        logger.info("VectorDBIntegration initialized successfully")
    
    def process_query(self, user_query):
        """
        Process a user query by retrieving context from the vector database
        and generating a response using the agents.
        
        Args:
            user_query (str): The user's original query
            
        Returns:
            str: The final response generated by the agents
        """
        logger.info(f"Processing query: '{user_query}'")
        
        # Generate related questions
        logger.info("Generating related questions...")
        questions = self.retriever.generate_questions(user_query)
        logger.info(f"Generated {len(questions)} related questions")
        
        # Retrieve context for the original query and all related questions
        all_contexts = []
        
        # First get context for original query
        logger.info("Retrieving context for original query...")
        original_context = self.retriever.get_context_for_query(user_query)
        logger.info(f"Retrieved {len(original_context)} context items for original query")
        all_contexts.extend(original_context)
        
        # Then get context for each related question - but limit to most relevant questions
        # to avoid context overload
        max_questions = 2  # Limit to just 2 additional questions
        for i, question in enumerate(questions[:max_questions]):
            logger.info(f"Retrieving context for related question {i+1}: '{question}'")
            context = self.retriever.get_context_for_query(question)
            logger.info(f"Retrieved {len(context)} context items for related question {i+1}")
            all_contexts.extend(context)
        
        # Format the retrieved contexts
        logger.info(f"Formatting {len(all_contexts)} total context items...")
        formatted_context = self._format_context(all_contexts)
        
        # Set up the agents and tasks
        logger.info("Setting up agents...")
        researcher = self.agents.researcher_agent()
        writer = self.agents.writer_agent()
        fact_checker = self.agents.fact_checker_agent()
        
        # Create tasks with the retrieved context
        logger.info("Creating research task with context...")
        research_task = self._create_research_task_with_context(user_query, formatted_context, researcher)
        logger.info("Creating writing task...")
        writing_task = self.tasks.writing_task(writer, "{research_results}", user_query)
        logger.info("Creating fact-checking task...")
        fact_checking_task = self.tasks.fact_checking_task(fact_checker, "{draft_response}", user_query)
        
        # Create and run the crew with iteration limits
        logger.info(f"Creating and running CrewAI with vector context (max_iterations: {self.max_iterations})...")
        crew = Crew(
            agents=[researcher, writer, fact_checker],
            tasks=[research_task, writing_task, fact_checking_task],
            verbose=True,
            process_timeout=self.process_timeout,  # Timeout in seconds
            max_rpm=None,  # No rate limiting for local execution
            max_iterations=self.max_iterations,  # Limit the number of iterations
            manager_llm_config={"temperature": 0.1}  # Lower temperature for more focused processing
        )
        
        # Run the crew process
        logger.info("Starting CrewAI process...")
        result = crew.kickoff()
        
        # Extract the text from the CrewOutput object
        result_text = str(result)
        logger.info(f"CrewAI process completed, result text length: {len(result_text)}")
        
        return result_text
    
    def _format_context(self, contexts):
        """Format the retrieved contexts into a single coherent string."""
        formatted = "КОНТЕКСТ ИЗ БАЗЫ ЗНАНИЙ СЕРГЕЯ:\n\n"
        
        # Deduplicate content by keeping track of seen contents
        seen_contents = set()
        
        # Track total context length to stay within limits
        max_context_length = 3000  # Limit total context length to 3000 characters
        current_length = len(formatted)
        num_fragments = 0
        
        # Sort by relevance if available - ensure most relevant content comes first
        sorted_contexts = sorted(contexts, key=lambda x: x.get('relevance', 0), reverse=True)
        
        for i, ctx in enumerate(sorted_contexts):
            content = ctx["content"]
            relevance = ctx.get("relevance", "unknown")
            
            # Skip duplicate content
            if content in seen_contents:
                continue
                
            # Truncate extremely long content entries
            if len(content) > 500:
                content = content[:500] + "... (truncated)"
            
            # Check if adding this content would exceed the maximum length
            if current_length + len(content) + 50 > max_context_length:
                # If we already have some context, skip adding more
                if num_fragments > 0:
                    logger.info(f"Reached context length limit ({current_length}/{max_context_length} chars). Stopping after {num_fragments} fragments.")
                    break
            
            # Add the content to seen contents
            seen_contents.add(content)
            
            # Format relevance value outside the f-string
            relevance_str = f"{relevance:.2f}" if isinstance(relevance, float) else str(relevance)
            
            # Add the formatted content with relevance score if available
            formatted += f"--- Фрагмент {num_fragments+1} (релевантность: {relevance_str}) ---\n"
            formatted += f"{content}\n\n"
            
            # Update the current length
            current_length += len(content) + 70  # Add buffer for the formatting
            num_fragments += 1
        
        logger.info(f"Formatted context: {current_length} characters, {num_fragments} unique fragments")
        return formatted
    
    def _create_research_task_with_context(self, query, context, agent):
        """Create a research task that includes the retrieved vector DB context."""
        logger.info("Creating research task with vector DB context")
        enhanced_query = f"""
{query}

ВАЖНО: Ниже предоставлен контекст из базы знаний Сергея Черненко. Это целевая информация, которая должна быть приоритетной для составления ответа.
Используйте этот контекст как основной источник для ответа, и обращайтесь к внешнему поиску только если информации недостаточно.
Ограничьтесь максимум 2 поисковыми запросами.

{context}
"""
        return self.tasks.research_task(agent, enhanced_query) 